---
apiVersion: v1
kind: Service
metadata:
  name: world-gift-art-service
  namespace: world-gift-art-prod
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    frontedBy: world-gift-art-prod # will be applied to backends by Spinnaker
  type: LoadBalancer
  loadBalancerIP: ""
