#from here all is executed, it needs to be executed 
#from the command line
secretGenerator:
- name: mysql-pass
  literals:
  - password=Passw0rd!
resources:
  - mysql-deployment.yaml
  - wordpress-deployment.yaml