steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t', 'gcr.io/$PROJECT_ID/pets-adopt:$COMMIT_SHA','./pets-adopt']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/$PROJECT_ID/pets-adopt:$COMMIT_SHA']
- name 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'  
  - 'deploy'
  - 'amazingapp'
  - '--image'
  - 'gcr.io/$PROJECT_ID/pets-adopt:$COMMIT_SHA'
  - '--region'
  - 'us-east1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
images:
- 'gcr.io/$PROJECT_ID/pets-adopt:$COMMIT_SHA'