apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  DB_Host: mysql
  DB_User: root
  DB_Password: Passw0rd

---------------------------------------------
apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
  labels:
    name: simple-webapp-color
spec:
  containers:
  - name: simple-webapp-color
    image: simple-webapp-color
    ports:
      - containerPort:8080
    envFrom:
    - secretRef:      
        name: app-secret
--------------------------------------------------
env:
  - name: DB_Password
    valueFrom:
      secretKeyRef:
        name:app-secret
        key: DB_Password

#or like this
volumes:
- name: app-secret-volume
  secret:
    secretName: app-secret