apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamcity-agent
spec:
  selector:
    matchLabels:
      app: teamcity-agent
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: teamcity-agent
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: teamcity-agent
          image: jetbrains/teamcity-agent        
          env:
          - name: SERVER_URL
            value: http://34.73.3.236:8080
          volumeMounts:
            - mountPath: "/data/teamcity_agent/conf"
              name: teamcitydata-agent
      volumes:
        - name: teamcitydata-agent
          emptyDir: {}      
      tolerations:
      - key: "spot-node-pool"
        value: "true"
        effect: NoSchedule
        operator: Equal
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - devops
---