apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  labels:
    app: pets2
  name: pets2
  namespace: default
spec:  
  replicas: 3  
  selector:
    matchLabels:
      app: pets2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:     
      labels:
        app: pets2
    spec:
      containers:
      - image: gcr.io/playground-s-11-466b1a34/pets-image:v3
        name: pets-image
---
apiVersion: v1
kind: Service
metadata:
  name: pets-service2
spec:
  type: LoadBalancer
  ports:
  - targetPort: 80
    port: 80
    nodePort: 30008
  selector:
    app: pets2